plugins {
    id 'java'
    id 'org.jetbrains.kotlin.jvm'
}

group = 'org'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

ext {
    jacksonVersion = '2.19.0'
    springVersion = '7.0.0-M5'
    bouncycastleVersion = '1.70'
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'

    implementation("com.fasterxml.jackson.core:jackson-databind:$jacksonVersion")
    implementation("com.fasterxml.jackson.core:jackson-core:$jacksonVersion")
    implementation("com.fasterxml.jackson.core:jackson-annotations:$jacksonVersion")

    implementation ("com.zaxxer:HikariCP:7.0.0")
    implementation("org.springframework:spring-context:$springVersion")
    implementation("org.springframework:spring-jdbc:$springVersion")
    implementation("org.springframework:spring-webflux:$springVersion")
    implementation("mysql:mysql-connector-java:8.0.33")
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
    implementation("com.github.mwiede:jsch:0.2.11")
    implementation("org.bouncycastle:bcprov-jdk15on:$bouncycastleVersion")
    implementation("org.bouncycastle:bcpkix-jdk15on:$bouncycastleVersion")
}

test {
    useJUnitPlatform()
}
kotlin {
    jvmToolchain(21)
}
